# Generated by Django 5.0.4 on 2024-04-11 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_code', models.CharField(max_length=500)),
                ('d_name', models.CharField(max_length=500)),
                ('duration', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('i_id', models.AutoField(primary_key=True, serialize=False)),
                ('i_code', models.CharField(max_length=500)),
                ('i_name', models.CharField(max_length=500)),
                ('i_password', models.CharField(max_length=500)),
                ('i_dp', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('university', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_code', models.CharField(max_length=500)),
                ('c_name', models.CharField(max_length=500)),
                ('credits', models.IntegerField()),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AttendEase.degree')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.CharField(max_length=500)),
                ('f_name', models.CharField(max_length=500)),
                ('f_dp', models.CharField(max_length=500)),
                ('university', models.CharField(max_length=500)),
                ('f_password', models.CharField(max_length=500)),
                ('i_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AttendEase.institute')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('sch_id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=500)),
                ('time', models.TimeField()),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AttendEase.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_no', models.CharField(max_length=500)),
                ('s_name', models.CharField(max_length=500)),
                ('semester', models.IntegerField()),
                ('degree', models.CharField(max_length=500)),
                ('s_password', models.CharField(max_length=500)),
                ('university', models.CharField(max_length=500)),
                ('s_dp', models.CharField(max_length=500)),
                ('img1', models.CharField(max_length=500)),
                ('img2', models.CharField(max_length=500)),
                ('img3', models.CharField(max_length=500)),
                ('img4', models.CharField(max_length=500)),
                ('img5', models.CharField(max_length=500)),
                ('i_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AttendEase.institute')),
            ],
        ),
        migrations.CreateModel(
            name='HasDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AttendEase.degree')),
                ('i_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AttendEase.institute')),
            ],
            options={
                'unique_together': {('i_id', 'd_id')},
            },
        ),
        migrations.CreateModel(
            name='Learns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.IntegerField()),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AttendEase.course')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AttendEase.student')),
            ],
            options={
                'unique_together': {('s_id', 'c_id')},
            },
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AttendEase.course')),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AttendEase.faculty')),
            ],
            options={
                'unique_together': {('f_id', 'c_id')},
            },
        ),
    ]
