# Generated by Django 5.0.4 on 2024-04-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendEase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='has_degree',
            field=models.ManyToManyField(to='AttendEase.degree'),
        ),
    ]
