# Generated by Django 5.0.4 on 2024-04-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendEase', '0002_institute_has_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='f_teaches',
            field=models.ManyToManyField(to='AttendEase.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='s_learns',
            field=models.ManyToManyField(to='AttendEase.course'),
        ),
    ]
