# Generated by Django 5.0.4 on 2024-04-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendEase', '0003_faculty_f_teaches_student_s_learns'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='no_classes',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
